CREATE TABLE IF NOT EXISTS app_sessions (
 token_hash CHAR(64) PRIMARY KEY,user_id INT UNSIGNED NOT NULL,expires_at DATETIME NOT NULL,
 KEY idx_sessions_expiry(expires_at),FOREIGN KEY(user_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS app_rate_limits (
 bucket CHAR(64) PRIMARY KEY,attempts INT UNSIGNED NOT NULL,expires_at DATETIME NOT NULL,KEY idx_rate_expiry(expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS app_proposal_sequences (
 year SMALLINT UNSIGNED PRIMARY KEY,number INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
