-- PostgreSQL/Supabase schema. Business dates remain DATE or local wall-clock TIMESTAMP
-- to preserve the original application semantics; session expiry is UTC.
CREATE TABLE IF NOT EXISTS clientes (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome varchar(120) NOT NULL, telefone varchar(30), email varchar(120),
 data_compra date NOT NULL, valor_orcamento numeric(12,2) NOT NULL DEFAULT 0,
 valor_vendido numeric(12,2) NOT NULL DEFAULT 0,
 status varchar(20) NOT NULL DEFAULT 'orcamento' CHECK (status IN ('orcamento','aprovado','em_andamento','entregue','cancelado')),
 forma_pagamento varchar(20) NOT NULL DEFAULT 'a_vista' CHECK (forma_pagamento IN ('a_vista','mensal','parcelas')),
 data_pagamento_vista date, valor_mensal numeric(12,2),
 dia_vencimento smallint CHECK (dia_vencimento BETWEEN 0 AND 255), data_inicio_mensalidade date,
 qtd_parcelas integer CHECK (qtd_parcelas >= 0), valor_parcela numeric(12,2),
 data_primeira_parcela date, parcelas_pagas integer DEFAULT 0 CHECK (parcelas_pagas >= 0),
 validade_orcamento date, data_aprovacao date, previsao_entrega date, data_entrega date,
 motivo_cancelamento varchar(255), dias_manutencao integer NOT NULL DEFAULT 90 CHECK (dias_manutencao >= 0),
 dias_renovacao integer NOT NULL DEFAULT 365 CHECK (dias_renovacao >= 0), observacoes text,
 documento_caminho varchar(255), documento_nome varchar(255), documento_tipo varchar(120),
 criado_em timestamp NOT NULL, atualizado_em timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_clientes_status ON clientes(status);
CREATE INDEX IF NOT EXISTS idx_clientes_data_compra ON clientes(data_compra);
CREATE INDEX IF NOT EXISTS idx_clientes_nome ON clientes(nome);
CREATE INDEX IF NOT EXISTS idx_clientes_forma_pagamento ON clientes(forma_pagamento);

CREATE TABLE IF NOT EXISTS usuarios (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome varchar(120) NOT NULL, email varchar(190) NOT NULL UNIQUE, senha_hash varchar(255),
 criado_em timestamp NOT NULL, atualizado_em timestamp NOT NULL, ultimo_acesso timestamp
);

INSERT INTO usuarios(nome,email,senha_hash,criado_em,atualizado_em)
SELECT 'Kauê Ajure','kaueajure@gmail.com',NULL,LOCALTIMESTAMP,LOCALTIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM usuarios WHERE email='kaueajure@gmail.com');

CREATE TABLE IF NOT EXISTS notas (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 cliente_id integer REFERENCES clientes(id) ON DELETE SET NULL,
 titulo varchar(160) NOT NULL, conteudo text NOT NULL,
 criada_em timestamp NOT NULL, atualizada_em timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_notas_cliente ON notas(cliente_id);
CREATE INDEX IF NOT EXISTS idx_notas_atualizada ON notas(atualizada_em);

CREATE TABLE IF NOT EXISTS produtos_servicos (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome varchar(160) NOT NULL, tipo_preco varchar(10) NOT NULL DEFAULT 'fixo' CHECK (tipo_preco IN ('fixo','hora')),
 preco numeric(12,2) NOT NULL DEFAULT 0, descricao text,
 ativo boolean NOT NULL DEFAULT true, ordem integer NOT NULL DEFAULT 0,
 criado_em timestamp NOT NULL, atualizado_em timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_produtos_ativo_ordem ON produtos_servicos(ativo,ordem);

CREATE TABLE IF NOT EXISTS propostas (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 codigo varchar(32) NOT NULL UNIQUE, token_publico char(64) NOT NULL UNIQUE,
 cliente_id integer REFERENCES clientes(id) ON DELETE SET NULL,
 titulo varchar(200) NOT NULL,
 status varchar(20) NOT NULL DEFAULT 'rascunho' CHECK (status IN ('rascunho','enviada','visualizada','aceita','recusada','expirada','cancelada')),
 validade date, desconto_valor numeric(12,2) NOT NULL DEFAULT 0,
 desconto_percentual numeric(5,2) NOT NULL DEFAULT 0,
 subtotal numeric(12,2) NOT NULL DEFAULT 0, total numeric(12,2) NOT NULL DEFAULT 0,
 condicoes text, escopo text, visualizada_em timestamp, respondida_em timestamp,
 resposta_cliente text, criada_em timestamp NOT NULL, atualizada_em timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_propostas_status ON propostas(status);
CREATE INDEX IF NOT EXISTS idx_propostas_cliente ON propostas(cliente_id);
CREATE INDEX IF NOT EXISTS idx_propostas_atualizada ON propostas(atualizada_em);

CREATE TABLE IF NOT EXISTS proposta_itens (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 proposta_id integer NOT NULL REFERENCES propostas(id) ON DELETE CASCADE,
 produto_id integer REFERENCES produtos_servicos(id) ON DELETE SET NULL,
 nome_snapshot varchar(160) NOT NULL, descricao_snapshot text,
 tipo_preco varchar(10) NOT NULL DEFAULT 'fixo' CHECK (tipo_preco IN ('fixo','hora')),
 preco_unitario numeric(12,2) NOT NULL DEFAULT 0, quantidade numeric(12,2) NOT NULL DEFAULT 1,
 total_linha numeric(12,2) NOT NULL DEFAULT 0, ordem integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_itens_proposta ON proposta_itens(proposta_id,ordem);

CREATE TABLE IF NOT EXISTS proposta_visualizacoes (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 proposta_id integer NOT NULL REFERENCES propostas(id) ON DELETE CASCADE,
 nome varchar(120) NOT NULL, visualizada_em timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_viz_proposta ON proposta_visualizacoes(proposta_id,visualizada_em);

CREATE TABLE IF NOT EXISTS app_sessions (
 token_hash char(64) PRIMARY KEY, user_id integer NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
 expires_at timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON app_sessions(expires_at);
CREATE TABLE IF NOT EXISTS app_rate_limits (
 bucket char(64) PRIMARY KEY, attempts integer NOT NULL CHECK (attempts >= 0), expires_at timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rate_expiry ON app_rate_limits(expires_at);
CREATE TABLE IF NOT EXISTS app_proposal_sequences (
 year smallint PRIMARY KEY, number integer NOT NULL CHECK (number >= 0)
);

-- Only the server-side database credential may read these tables. The project
-- does not use Supabase browser clients for business data.
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE notas ENABLE ROW LEVEL SECURITY;
ALTER TABLE produtos_servicos ENABLE ROW LEVEL SECURITY;
ALTER TABLE propostas ENABLE ROW LEVEL SECURITY;
ALTER TABLE proposta_itens ENABLE ROW LEVEL SECURITY;
ALTER TABLE proposta_visualizacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_proposal_sequences ENABLE ROW LEVEL SECURITY;

INSERT INTO storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
VALUES ('private-documents','private-documents',false,4194304,NULL)
ON CONFLICT (id) DO UPDATE SET public=false,file_size_limit=4194304;
